CREATE DATABASE IF NOT EXISTS KTX_BOOKING;
USE KTX_BOOKING;

CREATE TABLE USERS(
    USERS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(60) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PHONE VARCHAR(20),
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROUTES(
    ROUTES_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTURE_STATION VARCHAR(50) NOT NULL,
    ARRIVE_STATION VARCHAR(50) NOT NULL,
    UNIQUE(ARRIVE_STATION, DEPARTURE_STATION)
    );

CREATE TABLE SCHEDULES(
    SCHEDULES_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROUTES_ID INT NOT NULL,
    TRAIN_NUMBER VARCHAR(20) NOT NULL,
    DEPARTURE_TIME DATETIME,
    ARRIVE_TIME DATETIME,
    FOREIGN KEY (ROUTES_ID) REFERENCES ROUTES(ROUTES_ID)
    );

CREATE TABLE SEATS(
    SEATS_ID INT AUTO_INCREMENT PRIMARY KEY,
    SCHEDULES_ID INT NOT NULL,
    SEAT_NUMBER VARCHAR(10) NOT NULL,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'AVAILABLE',
    UNIQUE(SCHEDULES_ID, SEAT_NUMBER),
    FOREIGN KEY (SCHEDULES_ID) REFERENCES SCHEDULES(SCHEDULES_ID)
    );

CREATE TABLE TICKETS(
    TICKETS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERS_ID INT NOT NULL,
    SCHEDULES_ID INT NOT NULL,
    SEATS_ID INT NOT NULL,
    BARCODE VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID),
    FOREIGN KEY (SCHEDULES_ID) REFERENCES SCHEDULES(SCHEDULES_ID),
    FOREIGN KEY (SEATS_ID) REFERENCES SEATS(SEATS_ID),
    UNIQUE(SEATS_ID)
    );

CREATE TABLE PAYMENTS(
    PAYMENTS_ID INT AUTO_INCREMENT PRIMARY KEY,
    TICKETS_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    METHOD VARCHAR(20) NOT NULL,
    STATUS VARCHAR(15) NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY (TICKETS_ID) REFERENCES TICKETS(TICKETS_ID)
    );

CREATE TABLE SEASON_PASSES(
    PASSES_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERS_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID)
    );
